export const ADD_ARTICLE = 'ADD_ARTICLE'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const EDIT_ARTICLE = 'EDIT_ARTICLE'
export const GET_ARTICLES = 'GET_ARTICLES'
export const AVERAGE_READ_SPEED = 210